# Generated by Django 4.0.2 on 2022-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_fruits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fruits',
            field=models.CharField(max_length=15),
        ),
    ]
